### ISSUE TITLE
Support OLM v1

### ISSUE THREAD

**Issue by varad-ahirwadkar** [ocp-power-automation/rsct-operator#104]

**Comment by varad-ahirwadkar** [comment]
Tested using the PR: [Set the AllNamespaces installation mode to true](#105), 
**Install the extension:**
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: rsct-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsct-operator-installer
  namespace: rsct-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rsct-operator-installer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rsct-operator-installer
  namespace: rsct-operator-system
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: rsct-operator
spec:
  namespace: rsct-operator-system
  serviceAccount:
    name: rsct-operator-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: rsct-operator
      version: 0.0.1-alpha3
```
```
# oc get clusterextension
NAME            INSTALLED BUNDLE              VERSION        INSTALLED   PROGRESSING   AGE
rsct-operator   rsct-operator.v0.0.1-alpha3   0.0.1-alpha3   True        True          9s
```
**Patch the version in clusterextension**
```
# oc patch clusterextension rsct-operator  --type='merge' -p '{"spec": {"source": {"catalog": {"version": "0.0.1-alpha4"}}}}'
```
```
# oc get clusterextension -w
NAME            INSTALLED BUNDLE              VERSION        INSTALLED   PROGRESSING   AGE
rsct-operator   rsct-operator.v0.0.1-alpha3   0.0.1-alpha3   True        True          9s
rsct-operator   rsct-operator.v0.0.1-alpha3   0.0.1-alpha3   True        True          58s
rsct-operator   rsct-operator.v0.0.1-alpha4   0.0.1-alpha4   True        True          65s
```
